language: python
python: 3.6

sudo: false

install:
  - ./_tools/install-lookout-latest.sh
  - pip3 install -r requirements.txt
script:
  - (python3 sonarcheck_analyzer.py |& tee -a ../analyzer.log)&
  - ../lookout-sdk review --log-level=debug "ipv4://localhost:2022"

after_failure:
  - cat ../analyzer.log
  - cat ../lookout-install.log
